// apps/react-demo/src/DemoOptionsPanel.tsx
import type {
  CellValue,
  FeatureFlags,
  FeatureId,
  SpreadsheetInstance,
  ThemeName,
} from '@libraz/formulon-cell';
import { useSelection } from '@libraz/formulon-cell-react';
import { type ReactElement, useCallback, useMemo, useState } from 'react';
import {
  type ChangeLogEntry,
  type DemoCommandStrings,
  type DemoUiStrings,
  demoSelectionLabel,
  evaluateDemoProbe,
  FEATURE_GROUPS,
  isDemoFeatureOn,
  LOCALES,
  PRESETS,
  type PresetKey,
  THEMES,
} from '../../demo-shared/index.js';

interface DemoOptionsPanelProps {
  ui: DemoUiStrings;
  commandText: DemoCommandStrings;
  instance: SpreadsheetInstance | null;
  hidden: boolean;
  theme: ThemeName;
  locale: string;
  preset: PresetKey;
  features: FeatureFlags;
  ribbon: boolean;
  formatters: { uppercase: boolean; arrows: boolean };
  log: ChangeLogEntry[];
  onThemeChange: (theme: ThemeName) => void;
  onLocaleChange: (locale: string) => void;
  onPresetChange: (preset: PresetKey) => void;
  onFeatureToggle: (id: FeatureId) => void;
  onRibbonChange: (checked: boolean) => void;
  onFormatterChange: (key: 'uppercase' | 'arrows', checked: boolean) => void;
}

export const DemoOptionsPanel = ({
  ui,
  commandText,
  instance,
  hidden,
  theme,
  locale,
  preset,
  features,
  ribbon,
  formatters,
  log,
  onThemeChange,
  onLocaleChange,
  onPresetChange,
  onFeatureToggle,
  onRibbonChange,
  onFormatterChange,
}: DemoOptionsPanelProps): ReactElement => {
  const [probe, setProbe] = useState<{ name: string; result: string } | null>(null);
  const selection = useSelection(instance);
  const selectionLabel = useMemo(() => demoSelectionLabel(selection), [selection]);

  const runProbe = useCallback(
    (name: string, args: CellValue[]) => {
      if (!instance) return;
      setProbe(evaluateDemoProbe(instance, name, args));
    },
    [instance],
  );

  return (
    <aside className="demo__panel" aria-label={ui.optionsPanel} hidden={hidden}>
      <section className="demo__card">
        <h2>{ui.demoChrome}</h2>
        <div className="demo__controls demo__controls--panel">
          <div className="demo__seg" role="group" aria-label={ui.theme}>
            {THEMES.map((t) => (
              <button
                key={t.value}
                type="button"
                className={`demo__seg-btn${t.value === theme ? ' demo__seg-btn--active' : ''}`}
                onClick={() => onThemeChange(t.value)}
                aria-pressed={t.value === theme}
              >
                {ui.themeLabels[t.value] ?? t.label}
              </button>
            ))}
          </div>
          <div className="demo__seg" role="group" aria-label={ui.locale}>
            {LOCALES.map((l) => (
              <button
                key={l.value}
                type="button"
                className={`demo__seg-btn${l.value === locale ? ' demo__seg-btn--active' : ''}`}
                onClick={() => onLocaleChange(l.value)}
                aria-pressed={l.value === locale}
              >
                {l.label}
              </button>
            ))}
          </div>
        </div>
      </section>

      <section className="demo__card">
        <h2>{ui.preset}</h2>
        <p className="demo__hint">{ui.presetHint}</p>
        <div className="demo__preset">
          {PRESETS.map((p) => (
            <button
              key={p.value}
              type="button"
              className={`demo__preset-btn${p.value === preset ? ' demo__preset-btn--active' : ''}`}
              onClick={() => onPresetChange(p.value)}
              aria-pressed={p.value === preset}
            >
              <span className="demo__preset-name">{ui.presets[p.value]?.label ?? p.label}</span>
              <span className="demo__preset-hint">{ui.presets[p.value]?.hint ?? p.hint}</span>
            </button>
          ))}
        </div>
      </section>

      <section className="demo__card">
        <h2>{ui.features}</h2>
        <p className="demo__hint">{ui.featuresHint}</p>
        {FEATURE_GROUPS.map((group) => (
          <div key={group.title} className="demo__feat-group">
            <h3 className="demo__feat-title">
              {ui.featureGroupLabels[group.title] ?? group.title}
            </h3>
            <div className="demo__feat-grid">
              {group.features.map((f) => {
                const enabled = isDemoFeatureOn(features, f.id);
                return (
                  <label key={f.id} className={`demo__feat${enabled ? ' demo__feat--on' : ''}`}>
                    <input
                      type="checkbox"
                      checked={enabled}
                      onChange={() => onFeatureToggle(f.id)}
                    />
                    <span>{ui.featureLabels[f.id] ?? f.label}</span>
                  </label>
                );
              })}
              {group.title === 'Chrome' ? (
                <label className={`demo__feat${ribbon ? ' demo__feat--on' : ''}`}>
                  <input
                    type="checkbox"
                    checked={ribbon}
                    onChange={(e) => onRibbonChange(e.target.checked)}
                  />
                  <span>{ui.spreadsheetRibbon}</span>
                </label>
              ) : null}
            </div>
          </div>
        ))}
      </section>

      <section className="demo__card">
        <h2>{commandText.selection}</h2>
        <p className="demo__mono">{selectionLabel}</p>
      </section>

      <section className="demo__card">
        <h2>{ui.cellRenderers}</h2>
        <p className="demo__hint">{ui.cellRenderersHint}</p>
        <label className="fc-tb__check">
          <input
            type="checkbox"
            checked={formatters.uppercase}
            onChange={(e) => onFormatterChange('uppercase', e.target.checked)}
          />
          {ui.uppercaseColumnA}
        </label>
        <label className="fc-tb__check">
          <input
            type="checkbox"
            checked={formatters.arrows}
            onChange={(e) => onFormatterChange('arrows', e.target.checked)}
          />
          {ui.arrowPrefixNegatives}
        </label>
      </section>

      <section className="demo__card">
        <h2>{ui.customFunctions}</h2>
        <p className="demo__hint">{ui.customFunctionsHint}</p>
        <div className="demo__probe">
          <button
            type="button"
            className="fc-tb__btn fc-tb__btn--ghost"
            onClick={() => runProbe('GREET', [{ kind: 'text', value: 'Workbook' }])}
            disabled={!instance}
          >
            GREET("Workbook")
          </button>
          <button
            type="button"
            className="fc-tb__btn fc-tb__btn--ghost"
            onClick={() => runProbe('FAHRENHEIT', [{ kind: 'number', value: 100 }])}
            disabled={!instance}
          >
            FAHRENHEIT(100)
          </button>
          {probe ? (
            <p className="demo__probe-out">
              → <code>{probe.result}</code>
            </p>
          ) : null}
        </div>
      </section>

      <section className="demo__card demo__card--log">
        <h2>{ui.cellChangeLog}</h2>
        <p className="demo__hint">{ui.cellChangeLogHint}</p>
        {log.length === 0 ? (
          <p className="fc-tb__empty">{ui.editCellToSeeEvents}</p>
        ) : (
          <ul className="demo__log">
            {log.map((entry) => (
              <li key={entry.id}>
                <span className="demo__log-cell">{entry.cell}</span>
                <span className="demo__log-arrow">→</span>
                <span className="demo__mono">{entry.preview}</span>
              </li>
            ))}
          </ul>
        )}
      </section>
    </aside>
  );
};

// apps/vue-demo/src/DemoOptionsPanel.vue
<script setup lang="ts">
import type {
  CellValue,
  FeatureFlags,
  FeatureId,
  SpreadsheetInstance,
  ThemeName,
} from '@libraz/formulon-cell';
import { useSelection } from '@libraz/formulon-cell-vue';
import { computed, ref, toRef } from 'vue';
import {
  type ChangeLogEntry,
  type DemoCommandStrings,
  type DemoUiStrings,
  demoSelectionLabel,
  evaluateDemoProbe,
  FEATURE_GROUPS,
  isDemoFeatureOn,
  LOCALES,
  PRESETS,
  type PresetKey,
  THEMES,
} from '../../demo-shared/index.js';

const props = defineProps<{
  ui: DemoUiStrings;
  commandText: DemoCommandStrings;
  instance: SpreadsheetInstance | null;
  hidden: boolean;
  theme: ThemeName;
  locale: string;
  preset: PresetKey;
  features: FeatureFlags;
  /** Resolved ribbon visibility (drives the toggle's highlight). */
  ribbon: boolean;
  /** Requested ribbon visibility (drives the checkbox state). */
  showRibbon: boolean;
  formatters: { uppercase: boolean; arrows: boolean };
  log: ChangeLogEntry[];
}>();
const emit = defineEmits<{
  themeChange: [theme: ThemeName];
  localeChange: [locale: string];
  presetChange: [preset: PresetKey];
  featureToggle: [id: FeatureId];
  ribbonChange: [checked: boolean];
  formatterChange: [key: 'uppercase' | 'arrows', checked: boolean];
}>();

const probe = ref<{ name: string; result: string } | null>(null);
const selection = useSelection(toRef(props, 'instance'));
const selectionLabel = computed(() => demoSelectionLabel(selection.value));

const runProbe = (name: string, args: CellValue[]): void => {
  if (!props.instance) return;
  probe.value = evaluateDemoProbe(props.instance, name, args);
};
</script>

<template>
  <aside class="demo__panel" :aria-label="ui.optionsPanel" :hidden="hidden">
    <section class="demo__card">
      <h2>{{ ui.demoChrome }}</h2>
      <div class="demo__controls demo__controls--panel">
        <div class="demo__seg" role="group" :aria-label="ui.theme">
          <button
            v-for="t in THEMES"
            :key="t.value"
            type="button"
            :class="['demo__seg-btn', { 'demo__seg-btn--active': theme === t.value }]"
            :aria-pressed="theme === t.value"
            @click="emit('themeChange', t.value)"
          >
            {{ ui.themeLabels[t.value] ?? t.label }}
          </button>
        </div>
        <div class="demo__seg" role="group" :aria-label="ui.locale">
          <button
            v-for="l in LOCALES"
            :key="l.value"
            type="button"
            :class="['demo__seg-btn', { 'demo__seg-btn--active': locale === l.value }]"
            :aria-pressed="locale === l.value"
            @click="emit('localeChange', l.value)"
          >
            {{ l.label }}
          </button>
        </div>
      </div>
    </section>

    <section class="demo__card">
      <h2>{{ ui.preset }}</h2>
      <p class="demo__hint">{{ ui.presetHint }}</p>
      <div class="demo__preset">
        <button
          v-for="p in PRESETS"
          :key="p.value"
          type="button"
          :class="['demo__preset-btn', { 'demo__preset-btn--active': preset === p.value }]"
          :aria-pressed="preset === p.value"
          @click="emit('presetChange', p.value)"
        >
          <span class="demo__preset-name">{{ ui.presets[p.value]?.label ?? p.label }}</span>
          <span class="demo__preset-hint">{{ ui.presets[p.value]?.hint ?? p.hint }}</span>
        </button>
      </div>
    </section>

    <section class="demo__card">
      <h2>{{ ui.features }}</h2>
      <p class="demo__hint">{{ ui.featuresHint }}</p>
      <div v-for="group in FEATURE_GROUPS" :key="group.title" class="demo__feat-group">
        <h3 class="demo__feat-title">{{ ui.featureGroupLabels[group.title] ?? group.title }}</h3>
        <div class="demo__feat-grid">
          <label
            v-for="f in group.features"
            :key="f.id"
            :class="['demo__feat', { 'demo__feat--on': isDemoFeatureOn(features, f.id) }]"
          >
            <input
              type="checkbox"
              :checked="isDemoFeatureOn(features, f.id)"
              @change="emit('featureToggle', f.id)"
            />
            <span>{{ ui.featureLabels[f.id] ?? f.label }}</span>
          </label>
          <label
            v-if="group.title === 'Chrome'"
            :class="['demo__feat', { 'demo__feat--on': ribbon }]"
          >
            <input
              type="checkbox"
              :checked="showRibbon"
              @change="emit('ribbonChange', ($event.target as HTMLInputElement).checked)"
            />
            <span>{{ ui.spreadsheetRibbon }}</span>
          </label>
        </div>
      </div>
    </section>

    <section class="demo__card">
      <h2>{{ commandText.selection }}</h2>
      <p class="demo__mono">{{ selectionLabel }}</p>
    </section>

    <section class="demo__card">
      <h2>{{ ui.cellRenderers }}</h2>
      <p class="demo__hint">{{ ui.cellRenderersHint }}</p>
      <label class="fc-tb__check">
        <input
            type="checkbox"
            :checked="formatters.uppercase"
            @change="emit('formatterChange', 'uppercase', ($event.target as HTMLInputElement).checked)"
          />
        {{ ui.uppercaseColumnA }}
      </label>
      <label class="fc-tb__check">
        <input
            type="checkbox"
            :checked="formatters.arrows"
            @change="emit('formatterChange', 'arrows', ($event.target as HTMLInputElement).checked)"
          />
        {{ ui.arrowPrefixNegatives }}
      </label>
    </section>

    <section class="demo__card">
      <h2>{{ ui.customFunctions }}</h2>
      <p class="demo__hint">{{ ui.customFunctionsHint }}</p>
      <div class="demo__probe">
        <button
          type="button"
          class="fc-tb__btn fc-tb__btn--ghost"
          :disabled="!instance"
          @click="runProbe('GREET', [{ kind: 'text', value: 'Workbook' }])"
        >
          GREET("Workbook")
        </button>
        <button
          type="button"
          class="fc-tb__btn fc-tb__btn--ghost"
          :disabled="!instance"
          @click="runProbe('FAHRENHEIT', [{ kind: 'number', value: 100 }])"
        >
          FAHRENHEIT(100)
        </button>
        <p v-if="probe" class="demo__probe-out">
          → <code>{{ probe.result }}</code>
        </p>
      </div>
    </section>

    <section class="demo__card demo__card--log">
      <h2>{{ ui.cellChangeLog }}</h2>
      <p class="demo__hint">{{ ui.cellChangeLogHint }}</p>
      <p v-if="log.length === 0" class="fc-tb__empty">
        {{ ui.editCellToSeeEvents }}
      </p>
      <ul v-else class="demo__log">
        <li v-for="entry in log" :key="entry.id">
          <span class="demo__log-cell">{{ entry.cell }}</span>
          <span class="demo__log-arrow">→</span>
          <span class="demo__mono">{{ entry.preview }}</span>
        </li>
      </ul>
    </section>
  </aside>
</template>
